src/Entity/Materiel.php
<?php

namespace App\Entity;

use App\Repository\MaterielRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MaterielRepository::class)
 */
class Materiel
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="materiels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Fabricant::class, inversedBy="materiels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fabricant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $debut_commercialisation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fin_commercialisation;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix_public;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_court;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference_fabricant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = intval($id);

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getFabricant(): ?Fabricant
    {
        return $this->fabricant;
    }

    public function setFabricant(?Fabricant $fabricant): self
    {
        $this->fabricant = $fabricant;

        return $this;
    }

    public function getDebutCommercialisation(): ?string
    {
        return $this->debut_commercialisation;
    }

    public function setDebutCommercialisation(string $debut_commercialisation): self
    {
        $this->debut_commercialisation = $debut_commercialisation;

        return $this;
    }

    public function getFinCommercialisation(): ?string
    {
        return $this->fin_commercialisation;
    }

    public function setFinCommercialisation(?string $fin_commercialisation): self
    {
        $this->fin_commercialisation = $fin_commercialisation;

        return $this;
    }

    public function getPrixPublic(): ?float
    {
        return $this->prix_public;
    }

    public function setPrixPublic(?float $prix_public): self
    {
        $this->prix_public = $prix_public;

        return $this;
    }

    public function getNomCourt(): ?string
    {
        return $this->nom_court;
    }

    public function setNomCourt(string $nom_court): self
    {
        $this->nom_court = $nom_court;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getReferenceFabricant(): ?string
    {
        return $this->reference_fabricant;
    }

    public function setReferenceFabricant(string $reference_fabricant): self
    {
        $this->reference_fabricant = $reference_fabricant;

        return $this;
    }

    public function getSetters()
    {
        return [
            'materiel_id'               => 'setId',
            'type_id'                   => 'setType',
            'fabricant_id'              => 'setFabricant',
            'debut_commercialisation'   => 'setDebutCommercialisation',
            'fin_commercialisation'     => 'setFinCommercialisation',
            'prix_public'               => 'setPrixPublic',
            'nom_court'                 => 'setNomCourt',
            'nom'                       => 'setNom',
            'marque'                    => 'setMarque',
            'reference_fabricant'       => 'setReferenceFabricant'
        ];
    }

}

src/Controller/MaterielController.php
<?php

namespace App\Controller;

use App\Service\HydrationService;
use App\Service\MaterielService;

use App\Entity\Materiel;
use App\Form\MaterielFormType;
use App\Repository\MaterielRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/")
 */
class MaterielController extends AbstractController
{
    /**
     * @Route("/", name="materiel_index", methods={"GET"})
     */
    public function index(MaterielRepository $materielRepository, Request $request): Response
    {
        $form       = $this->createForm(MaterielFormType::class);
            
        return $this->render('materiel/index.html.twig', [
            'materiels' => $materielRepository->findAll(),
            'form'      => $form->createView()
        ]);
    }

    /**
     * @Route("/hydrate", name="materiel_hydrate", methods={"POST"})
     */
    public function hydrate(MaterielRepository $materielRepository, Request $request, HydrationService $hydS): Response
    {
        $result = $hydS->insertToDatabase();

        //return new JsonResponse($result);
        return $this->render('materiel/table.html.twig', [
            'materiels' => $materielRepository->findAll(),
            'success'   => $result['success'],
            'message'   => $result['message']
        ]);
    }

    /**
     * @Route("/search", name="materiel_search", methods={"POST"})
     */
    public function search(Request $request, MaterielRepository $materielRepository): Response
    {
        $materiels = $materielRepository->findBySearch($request->request->all());
        
        return $this->render('materiel/table.html.twig', [
            'materiels' => $materiels
        ]);
    }

    /**
     * @Route("/new", name="materiel_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $materiel = new Materiel();
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($materiel);
            $entityManager->flush();

            return $this->redirectToRoute('materiel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiel/new.html.twig', [
            'materiel' => $materiel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/show", name="materiel_show", methods={"POST"})
     */
    public function show(Request $request, MaterielRepository $materielRepository): Response
    {
        $materiel = $materielRepository->findById($request->request->get('id'))[0];

        return $this->render('materiel/show.html.twig', [
            'materiel' => $materiel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="materiel_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Materiel $materiel): Response
    {
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('materiel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiel/edit.html.twig', [
            'materiel' => $materiel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="materiel_delete", methods={"POST"})
     */
    public function delete(Request $request, Materiel $materiel): Response
    {
        if ($this->isCsrfTokenValid('delete'.$materiel->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($materiel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('materiel_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/materiel/_delete_form.html.twig
<form method="post" action="{{ path('materiel_delete', {'id': materiel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ materiel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/materiel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/materiel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Materiel{% endblock %}

{% block body %}
    <h1>Edit Materiel</h1>

    {{ include('materiel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('materiel_index') }}">back to list</a>

    {{ include('materiel/_delete_form.html.twig') }}
{% endblock %}

templates/materiel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materiel index{% endblock %}

{% block body %}
    <img class="d-block m-auto" src="https://marquedigitale.fr/wp-content/uploads/2020/05/logo-marquedigitale.svg" alt="Logo Marque Digitale">

    <div class="position-absolute start-0 top-0 m-1">
        <a href="https://github.com/olivier-maurel/md-test-api" target="_blank" title="Se diriger vers le repository GitHub de mon premier essai : tentative de génération automatique d'une base de donnée." class="btn btn-sm btn-primary">1erGit</a>
        <a href="https://github.com/olivier-maurel/test-marquedigitale" target="_blank" title="Se diriger vers le repository GitHub de mon deuxième essai (celui-ci) : la base de donnée ainsi que les tables ne sont pas généré automatiquement mais les insertions le sont. La barre de recherche est en asynchrone et il est possible de cliquer sur un produit pour obtenir 'plus' d'informations." class="btn btn-sm btn-primary">2emeGit</a>
        <a href="{{ asset('assets/files/database.sql') }}" title="Obtenir le fichier SQL de la base de donnée" class="btn btn-sm btn-success">SQL File</a>
        <a href="{{ asset('assets/files/schema-db.pdf') }}" target="_blank" title="Le schema de la base de donnée" class="btn btn-sm btn-warning">SchemaDB</a>
        <a href="{{ asset('assets/files/readme.md') }}" title="Un petit texte explicatif sur ma démarche pour répondre à la mission" class="btn btn-sm btn-info">ReadMe</a>
    </div>

    <button class="btn btn-sm btn-danger position-absolute end-0 top-0 m-1" id="generate" title="Attention! Vous êtes sur le point de regénérer la base de donnée, les tables seront vidés puis les données seront réinsérées. Pour plus d'info -> 'src/Service/HydrationService'">Regénérer la base de donnée</button>

    {{ form_start(form) }}
        <div class="">
            <div class="m-auto my-5 p-2" style="width: max-content; background-color: #c18484;">
                <div class="d-flex justify-content-center">
                    {{ form_row(form.search) }}
                </div>
                <div class="d-flex justify-content-center">
                    {{ form_row(form.famille) }}
                    {{ form_row(form.marque) }}
                </div>
            </div>
        </div>
    {{ form_end(form) }}

    <div class="content-table">
        {% include 'materiel/table.html.twig' %}
    </div>

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>

    $(document.body).on('change', '.search-item', function(){
        setFormData();
    });
    $(document.body).on('keyup', '.search-item', function(){
        setFormData();
    });

    $(document.body).on('click', 'tr[data-id]', function(){      
        $.post("{{ path('materiel_show') }}", {'id': $(this).attr('data-id')}, function(data){
            $('.modal-content').html(data);
        });
    });

    $(document.body).on('click', '#generate', function(){      
        $.post("{{ path('materiel_hydrate') }}", function(data){
            $('.content-table').html(data);
            $('#dbAlert').removeClass('d-none');
            setTimeout(function() {
                $('#dbAlert').addClass('d-none');
            }, 5000);
        });
    });

    function setFormData()
    {
        $formData = new FormData();
        $formData.append('search', $('#materiel_form_search').val());
        $formData.append('famille', $('#materiel_form_famille').val());
        $formData.append('marque', $('#materiel_form_marque').val());
       
        $.ajax({
          method: "POST",
          url: "{{ path('materiel_search') }}",
          cache: false,
          contentType: false,
          processData: false,
          data: $formData
        }).then(function(result){
            $('.content-table').html(result);
        });
    }



</script>
{% endblock %}

templates/materiel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Materiel{% endblock %}

{% block body %}
    <h1>Create new Materiel</h1>

    {{ include('materiel/_form.html.twig') }}

    <a href="{{ path('materiel_index') }}">back to list</a>
{% endblock %}

templates/materiel/show.html.twig
<table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ materiel.id }}</td>
        </tr>
        <tr>
            <th>Nom_court</th>
            <td>{{ materiel.nomCourt }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ materiel.nom }}</td>
        </tr>
        <tr>
            <th>Marque</th>
            <td>{{ materiel.marque }}</td>
        </tr>
        <tr>
            <th>Prix_public</th>
            <td>{{ materiel.prixPublic }}</td>
        </tr>
        <tr>
            <th>Reference_fabricant</th>
            <td>{{ materiel.referenceFabricant }}</td>
        </tr>
        <tr>
            <th>Debut Commercialisation</th>
            <td>{{ materiel.debutCommercialisation }}</td>
        </tr>
        <tr>
            <th>Fin Commercialisation</th>
            <td>{{ materiel.finCommercialisation }}</td>
        </tr>
    </tbody>
</table>

templates/materiel/table.html.twig
<table class="table table-hover table-striped small w-auto m-auto">
    <thead class="text-white">
        <tr style="background-color: rgb(80, 80, 80);">
            <th>materiel_id</th>
            <th>nom_court</th>
            <th>marque</th>
            <th>prix_public</th>
            <th>reference_fabricant</th>
            <th>type</th>
            <th>metier</th>
        </tr>
    </thead>
    <tbody id="tbody">
        {% for materiel in materiels %}
            <tr class="bg-light" data-id="{{ materiel.id }}" style="cursor: pointer;" data-toggle="modal" data-target=".bd-example-modal-lg">
                <td>{{ materiel.id }}</td>
                <td>{{ materiel.nomCourt }}</td>
                <td>{{ materiel.marque }}</td>
                <td>{{ materiel.prixPublic }}</td>
                <td>{{ materiel.referenceFabricant }}</td>
                <td>{{ materiel.type.nom }}</td>
                <td>{{ materiel.type.metier.nom }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Aucun produit trouvé :/</td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<div id="dbAlert" class="alert alert-{% if success is defined and success == true %}success{% else %}danger{% endif %} d-none" role="alert" style="position: fixed; top: 15px; left: 50%; transform: translateX(-50%);">
    <h4>Rapport de la génération de la base de données.</h4>
    <small id="message">
        {% if message is defined %}{{ message | raw }}{% endif %}
    </small>
</div>